config/routes.rb
Rails.application.routes.draw do

  resources :todos

  root to: 'todos#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord

  validates :title, presence: true, length: { minimum: 3 }

  def done!
    self.update_attributes(done: true) if !self.done
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

  def index
    @todos = Todo.all.order(created_at: "DESC")
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    if @todo.save
      flash[:notice] = "Todo created!"
      redirect_to todos_path
    else
      flash[:alert] = "Error while creating todo"
      render :new
    end
  end

  def destroy
    @todo = Todo.find(params[:id])
    if @todo && @todo.destroy
      flash[:notice] = "Todo removed!"
      redirect_to todos_path and return
    end
    flash[:alert] = "Couldn't remove Todo!"
    redirect_to todos_path
  end

  protected

  def todo_params
    params.require(:todo).permit(:title)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsOnKubernetes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>

    <% flash.each do |type, msg| %>
      <div class="<%= type %>">
        <%= msg %>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/todos/index.html.erb
<div id="todos">
  <div class="parent white">

    <div class="box new">
      <%= link_to "Add", new_todo_path, class: "btn" %>
    </div>

    <% @todos.each do |todo| %>

      <div class="box">
        <%= todo.title %>

        <%= form_with model: todo, method: "delete" do |f| %>
          <%= f.submit "Done!", class: "btn" %>
        <% end %>

      </div>

    <% end %>
  </div>
</div>

app/views/todos/new.html.erb
<% unless @todo.errors.empty? %>
  <div class="alert">
   <%= @todo.errors.full_messages.join(" ") %>
  </div>
<% end %>

<%= form_with model: @todo do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.submit "Create", class: "btn" %>
<% end %>